// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsShortUrlNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ShortUrlErrorReason_ShortUrl_NotFound.String() && e.Code == 100
}

// 为某个枚举单独设置错误码
func ErrorShortUrlNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(100, ShortUrlErrorReason_ShortUrl_NotFound.String(), fmt.Sprintf(format, args...))
}
